sudo: required
services:
  - docker

before_install:
  - docker build -t "morfioce/docker-react" -f "Dockerfile.dev" .

script:
  - docker run "morfioce/docker-react" npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-east-2-782719482880"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secret: "$AWS_SECRET_KEY"